// <auto-generated />
using System;
using Laraue.Apps.RealEstate.DataAccess;
using Laraue.Apps.RealEstate.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.RealEstate.Db.Migrations
{
    [DbContext(typeof(AdvertisementsDbContext))]
    [Migration("20230612094634_DropCrawlerTable")]
    partial class DropCrawlerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.Advertisement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<decimal>("Ideality")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ideality");

                    b.Property<decimal?>("RenovationRating")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("renovation_rating");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("rooms_count");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<decimal>("Square")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("square");

                    b.Property<decimal>("SquareMeterPredictedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("square_meter_predicted_price");

                    b.Property<decimal>("SquareMeterPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("square_meter_price");

                    b.Property<int>("TotalFloorsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("total_floors_number");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_advertisements");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_advertisements_source_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_advertisements_updated_at");

                    b.ToTable("advertisements", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.AdvertisementImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdvertisementId")
                        .HasColumnType("bigint")
                        .HasColumnName("advertisement_id");

                    b.Property<bool?>("IsPictureRelevant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_picture_relevant");

                    b.Property<bool?>("IsRenovationExists")
                        .HasColumnType("boolean")
                        .HasColumnName("is_renovation_exists");

                    b.Property<decimal?>("RenovationRating")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("renovation_rating");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_advertisement_images");

                    b.HasIndex("AdvertisementId")
                        .HasDatabaseName("ix_advertisement_images_advertisement_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_advertisement_images_url");

                    b.ToTable("advertisement_images", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.AdvertisementTransportStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdvertisementId")
                        .HasColumnType("bigint")
                        .HasColumnName("advertisement_id");

                    b.Property<int>("DistanceInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("distance_in_minutes");

                    b.Property<int>("DistanceType")
                        .HasColumnType("integer")
                        .HasColumnName("distance_type");

                    b.Property<long>("TransportStopId")
                        .HasColumnType("bigint")
                        .HasColumnName("transport_stop_id");

                    b.HasKey("Id")
                        .HasName("pk_advertisement_transport_stops");

                    b.HasIndex("AdvertisementId")
                        .HasDatabaseName("ix_advertisement_transport_stops_advertisement_id");

                    b.HasIndex("TransportStopId", "AdvertisementId")
                        .IsUnique()
                        .HasDatabaseName("ix_advertisement_transport_stops_transport_stop_id_advertiseme");

                    b.ToTable("advertisement_transport_stops", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.CrawlingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_crawling_sessions");

                    b.ToTable("crawling_sessions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.CrawlingSessionAdvertisement", b =>
                {
                    b.Property<long>("AdvertisementId")
                        .HasColumnType("bigint")
                        .HasColumnName("advertisement_id");

                    b.Property<Guid>("CrawlingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawling_session_id");

                    b.HasKey("AdvertisementId", "CrawlingSessionId")
                        .HasName("pk_crawling_session_advertisements");

                    b.HasIndex("CrawlingSessionId")
                        .HasDatabaseName("ix_crawling_session_advertisements_crawling_session_id");

                    b.ToTable("crawling_session_advertisements", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.TransportStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("pk_transport_stops");

                    b.ToTable("transport_stops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#cf0000",
                            Name = "Девяткино",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#cf0000",
                            Name = "Гражданский проспект",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#cf0000",
                            Name = "Академическая",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#cf0000",
                            Name = "Политехническая",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#cf0000",
                            Name = "Площадь Мужества",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#cf0000",
                            Name = "Лесная",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#cf0000",
                            Name = "Выборгская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#cf0000",
                            Name = "Площадь Ленина",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#cf0000",
                            Name = "Чернышевская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 10L,
                            Color = "#cf0000",
                            Name = "Площадь Восстания",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 11L,
                            Color = "#cf0000",
                            Name = "Владимирская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 12L,
                            Color = "#cf0000",
                            Name = "Пушкинская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 13L,
                            Color = "#03238b",
                            Name = "Технологический институт",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 14L,
                            Color = "#cf0000",
                            Name = "Балтийская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 15L,
                            Color = "#cf0000",
                            Name = "Нарвская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 16L,
                            Color = "#cf0000",
                            Name = "Кировский завод",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 17L,
                            Color = "#cf0000",
                            Name = "Автово",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 18L,
                            Color = "#cf0000",
                            Name = "Ленинский проспект",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 19L,
                            Color = "#cf0000",
                            Name = "Проспект Ветеранов",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 20L,
                            Color = "#03238b",
                            Name = "Парнас",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 21L,
                            Color = "#03238b",
                            Name = "Проспект Просвещения",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 22L,
                            Color = "#03238b",
                            Name = "Озерки",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 23L,
                            Color = "#03238b",
                            Name = "Удельная",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 24L,
                            Color = "#03238b",
                            Name = "Пионерская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 25L,
                            Color = "#03238b",
                            Name = "Черная речка",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 26L,
                            Color = "#03238b",
                            Name = "Петроградская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 27L,
                            Color = "#03238b",
                            Name = "Горьковская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 28L,
                            Color = "#03238b",
                            Name = "Невский проспект",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 29L,
                            Color = "#03238b",
                            Name = "Сенная площадь",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 30L,
                            Color = "#03238b",
                            Name = "Фрунзенская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 31L,
                            Color = "#03238b",
                            Name = "Московские Ворота",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 32L,
                            Color = "#03238b",
                            Name = "Электросила",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 33L,
                            Color = "#03238b",
                            Name = "Парк Победы",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 34L,
                            Color = "#03238b",
                            Name = "Московская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 35L,
                            Color = "#03238b",
                            Name = "Звездная",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 36L,
                            Color = "#03238b",
                            Name = "Купчино",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 37L,
                            Color = "#00701a",
                            Name = "Приморская",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 38L,
                            Color = "#00701a",
                            Name = "Василеостровская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 39L,
                            Color = "#00701a",
                            Name = "Гостиный Двор",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 40L,
                            Color = "#00701a",
                            Name = "Маяковская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 41L,
                            Color = "#ff7f00",
                            Name = "Площадь Александра Невского",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 42L,
                            Color = "#00701a",
                            Name = "Елизаровская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 43L,
                            Color = "#00701a",
                            Name = "Ломоносовская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 44L,
                            Color = "#00701a",
                            Name = "Пролетарская",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 45L,
                            Color = "#00701a",
                            Name = "Обухово",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 46L,
                            Color = "#00701a",
                            Name = "Рыбацкое",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 47L,
                            Color = "#94007c",
                            Name = "Комендантский проспект",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 48L,
                            Color = "#94007c",
                            Name = "Старая Деревня",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 49L,
                            Color = "#94007c",
                            Name = "Крестовский остров",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 50L,
                            Color = "#94007c",
                            Name = "Чкаловская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 51L,
                            Color = "#94007c",
                            Name = "Спортивная",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 52L,
                            Color = "#94007c",
                            Name = "Садовая",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 53L,
                            Color = "#ff7f00",
                            Name = "Достоевская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 54L,
                            Color = "#ff7f00",
                            Name = "Лиговский проспект",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 55L,
                            Color = "#ff7f00",
                            Name = "Новочеркасская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 56L,
                            Color = "#ff7f00",
                            Name = "Ладожская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 57L,
                            Color = "#ff7f00",
                            Name = "Проспект Большевиков",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 58L,
                            Color = "#ff7f00",
                            Name = "Улица Дыбенко",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 59L,
                            Color = "#94007c",
                            Name = "Волковская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 60L,
                            Color = "#94007c",
                            Name = "Звенигородская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 61L,
                            Color = "#ff7f00",
                            Name = "Спасская",
                            Priority = (byte)1
                        },
                        new
                        {
                            Id = 62L,
                            Color = "#94007c",
                            Name = "Обводный канал",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 63L,
                            Color = "#94007c",
                            Name = "Адмиралтейская",
                            Priority = (byte)2
                        },
                        new
                        {
                            Id = 64L,
                            Color = "#94007c",
                            Name = "Международная",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 65L,
                            Color = "#94007c",
                            Name = "Бухарестская",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 66L,
                            Color = "#00701a",
                            Name = "Беговая",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 67L,
                            Color = "#00701a",
                            Name = "Новокрестовская",
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 68L,
                            Color = "#94007c",
                            Name = "Проспект Славы",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 69L,
                            Color = "#94007c",
                            Name = "Дунайская",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 70L,
                            Color = "#94007c",
                            Name = "Шушары",
                            Priority = (byte)4
                        },
                        new
                        {
                            Id = 71L,
                            Color = "#ff7f00",
                            Name = "Горный институт",
                            Priority = (byte)4
                        });
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.TransportStopExternalId", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<long>("TransportStopId")
                        .HasColumnType("bigint")
                        .HasColumnName("transport_stop_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_stop_external_ids");

                    b.HasIndex("TransportStopId")
                        .HasDatabaseName("ix_transport_stop_external_ids_transport_stop_id");

                    b.ToTable("transport_stop_external_ids", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExternalId = "167",
                            Source = 0,
                            TransportStopId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ExternalId = "168",
                            Source = 0,
                            TransportStopId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ExternalId = "169",
                            Source = 0,
                            TransportStopId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            ExternalId = "170",
                            Source = 0,
                            TransportStopId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            ExternalId = "171",
                            Source = 0,
                            TransportStopId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            ExternalId = "172",
                            Source = 0,
                            TransportStopId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            ExternalId = "173",
                            Source = 0,
                            TransportStopId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            ExternalId = "174",
                            Source = 0,
                            TransportStopId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            ExternalId = "175",
                            Source = 0,
                            TransportStopId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            ExternalId = "176",
                            Source = 0,
                            TransportStopId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            ExternalId = "177",
                            Source = 0,
                            TransportStopId = 11L
                        },
                        new
                        {
                            Id = 12L,
                            ExternalId = "178",
                            Source = 0,
                            TransportStopId = 12L
                        },
                        new
                        {
                            Id = 13L,
                            ExternalId = "179",
                            Source = 0,
                            TransportStopId = 13L
                        },
                        new
                        {
                            Id = 14L,
                            ExternalId = "180",
                            Source = 0,
                            TransportStopId = 14L
                        },
                        new
                        {
                            Id = 15L,
                            ExternalId = "181",
                            Source = 0,
                            TransportStopId = 15L
                        },
                        new
                        {
                            Id = 16L,
                            ExternalId = "182",
                            Source = 0,
                            TransportStopId = 16L
                        },
                        new
                        {
                            Id = 17L,
                            ExternalId = "183",
                            Source = 0,
                            TransportStopId = 17L
                        },
                        new
                        {
                            Id = 18L,
                            ExternalId = "184",
                            Source = 0,
                            TransportStopId = 18L
                        },
                        new
                        {
                            Id = 19L,
                            ExternalId = "185",
                            Source = 0,
                            TransportStopId = 19L
                        },
                        new
                        {
                            Id = 20L,
                            ExternalId = "186",
                            Source = 0,
                            TransportStopId = 20L
                        },
                        new
                        {
                            Id = 21L,
                            ExternalId = "187",
                            Source = 0,
                            TransportStopId = 21L
                        },
                        new
                        {
                            Id = 22L,
                            ExternalId = "188",
                            Source = 0,
                            TransportStopId = 22L
                        },
                        new
                        {
                            Id = 23L,
                            ExternalId = "189",
                            Source = 0,
                            TransportStopId = 23L
                        },
                        new
                        {
                            Id = 24L,
                            ExternalId = "190",
                            Source = 0,
                            TransportStopId = 24L
                        },
                        new
                        {
                            Id = 25L,
                            ExternalId = "191",
                            Source = 0,
                            TransportStopId = 25L
                        },
                        new
                        {
                            Id = 26L,
                            ExternalId = "192",
                            Source = 0,
                            TransportStopId = 26L
                        },
                        new
                        {
                            Id = 27L,
                            ExternalId = "193",
                            Source = 0,
                            TransportStopId = 27L
                        },
                        new
                        {
                            Id = 28L,
                            ExternalId = "194",
                            Source = 0,
                            TransportStopId = 28L
                        },
                        new
                        {
                            Id = 29L,
                            ExternalId = "195",
                            Source = 0,
                            TransportStopId = 29L
                        },
                        new
                        {
                            Id = 30L,
                            ExternalId = "197",
                            Source = 0,
                            TransportStopId = 30L
                        },
                        new
                        {
                            Id = 31L,
                            ExternalId = "198",
                            Source = 0,
                            TransportStopId = 31L
                        },
                        new
                        {
                            Id = 32L,
                            ExternalId = "199",
                            Source = 0,
                            TransportStopId = 32L
                        },
                        new
                        {
                            Id = 33L,
                            ExternalId = "200",
                            Source = 0,
                            TransportStopId = 33L
                        },
                        new
                        {
                            Id = 34L,
                            ExternalId = "201",
                            Source = 0,
                            TransportStopId = 34L
                        },
                        new
                        {
                            Id = 35L,
                            ExternalId = "202",
                            Source = 0,
                            TransportStopId = 35L
                        },
                        new
                        {
                            Id = 36L,
                            ExternalId = "203",
                            Source = 0,
                            TransportStopId = 36L
                        },
                        new
                        {
                            Id = 37L,
                            ExternalId = "204",
                            Source = 0,
                            TransportStopId = 37L
                        },
                        new
                        {
                            Id = 38L,
                            ExternalId = "205",
                            Source = 0,
                            TransportStopId = 38L
                        },
                        new
                        {
                            Id = 39L,
                            ExternalId = "206",
                            Source = 0,
                            TransportStopId = 39L
                        },
                        new
                        {
                            Id = 40L,
                            ExternalId = "207",
                            Source = 0,
                            TransportStopId = 40L
                        },
                        new
                        {
                            Id = 41L,
                            ExternalId = "208",
                            Source = 0,
                            TransportStopId = 41L
                        },
                        new
                        {
                            Id = 42L,
                            ExternalId = "210",
                            Source = 0,
                            TransportStopId = 42L
                        },
                        new
                        {
                            Id = 43L,
                            ExternalId = "211",
                            Source = 0,
                            TransportStopId = 43L
                        },
                        new
                        {
                            Id = 44L,
                            ExternalId = "212",
                            Source = 0,
                            TransportStopId = 44L
                        },
                        new
                        {
                            Id = 45L,
                            ExternalId = "213",
                            Source = 0,
                            TransportStopId = 45L
                        },
                        new
                        {
                            Id = 46L,
                            ExternalId = "214",
                            Source = 0,
                            TransportStopId = 46L
                        },
                        new
                        {
                            Id = 47L,
                            ExternalId = "215",
                            Source = 0,
                            TransportStopId = 47L
                        },
                        new
                        {
                            Id = 48L,
                            ExternalId = "216",
                            Source = 0,
                            TransportStopId = 48L
                        },
                        new
                        {
                            Id = 49L,
                            ExternalId = "217",
                            Source = 0,
                            TransportStopId = 49L
                        },
                        new
                        {
                            Id = 50L,
                            ExternalId = "218",
                            Source = 0,
                            TransportStopId = 50L
                        },
                        new
                        {
                            Id = 51L,
                            ExternalId = "219",
                            Source = 0,
                            TransportStopId = 51L
                        },
                        new
                        {
                            Id = 52L,
                            ExternalId = "220",
                            Source = 0,
                            TransportStopId = 52L
                        },
                        new
                        {
                            Id = 53L,
                            ExternalId = "221",
                            Source = 0,
                            TransportStopId = 53L
                        },
                        new
                        {
                            Id = 54L,
                            ExternalId = "222",
                            Source = 0,
                            TransportStopId = 54L
                        },
                        new
                        {
                            Id = 55L,
                            ExternalId = "224",
                            Source = 0,
                            TransportStopId = 55L
                        },
                        new
                        {
                            Id = 56L,
                            ExternalId = "225",
                            Source = 0,
                            TransportStopId = 56L
                        },
                        new
                        {
                            Id = 57L,
                            ExternalId = "226",
                            Source = 0,
                            TransportStopId = 57L
                        },
                        new
                        {
                            Id = 58L,
                            ExternalId = "227",
                            Source = 0,
                            TransportStopId = 58L
                        },
                        new
                        {
                            Id = 59L,
                            ExternalId = "230",
                            Source = 0,
                            TransportStopId = 59L
                        },
                        new
                        {
                            Id = 60L,
                            ExternalId = "231",
                            Source = 0,
                            TransportStopId = 60L
                        },
                        new
                        {
                            Id = 61L,
                            ExternalId = "232",
                            Source = 0,
                            TransportStopId = 61L
                        },
                        new
                        {
                            Id = 62L,
                            ExternalId = "241",
                            Source = 0,
                            TransportStopId = 62L
                        },
                        new
                        {
                            Id = 63L,
                            ExternalId = "242",
                            Source = 0,
                            TransportStopId = 63L
                        },
                        new
                        {
                            Id = 64L,
                            ExternalId = "246",
                            Source = 0,
                            TransportStopId = 64L
                        },
                        new
                        {
                            Id = 65L,
                            ExternalId = "247",
                            Source = 0,
                            TransportStopId = 65L
                        },
                        new
                        {
                            Id = 66L,
                            ExternalId = "355",
                            Source = 0,
                            TransportStopId = 66L
                        },
                        new
                        {
                            Id = 67L,
                            ExternalId = "356",
                            Source = 0,
                            TransportStopId = 67L
                        },
                        new
                        {
                            Id = 68L,
                            ExternalId = "357",
                            Source = 0,
                            TransportStopId = 68L
                        },
                        new
                        {
                            Id = 69L,
                            ExternalId = "358",
                            Source = 0,
                            TransportStopId = 69L
                        },
                        new
                        {
                            Id = 70L,
                            ExternalId = "359",
                            Source = 0,
                            TransportStopId = 70L
                        },
                        new
                        {
                            Id = 71L,
                            ExternalId = "382",
                            Source = 0,
                            TransportStopId = 71L
                        });
                });

            modelBuilder.Entity("Laraue.Core.Extensions.Hosting.EfCore.JobStateEntity", b =>
                {
                    b.Property<string>("JobName")
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<string>("JobData")
                        .HasColumnType("text")
                        .HasColumnName("job_data");

                    b.Property<DateTime?>("LastExecutionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_execution_at");

                    b.Property<DateTime?>("NextExecutionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_execution_at");

                    b.HasKey("JobName")
                        .HasName("pk_job_states");

                    b.ToTable("job_states", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.AdvertisementImage", b =>
                {
                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advertisement_images_advertisements_advertisement_id");

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.AdvertisementTransportStop", b =>
                {
                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.Advertisement", "Advertisement")
                        .WithMany("TransportStops")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advertisement_transport_stops_advertisements_advertisement_");

                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.TransportStop", "TransportStop")
                        .WithMany()
                        .HasForeignKey("TransportStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advertisement_transport_stops_transport_stops_transport_sto");

                    b.Navigation("Advertisement");

                    b.Navigation("TransportStop");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.CrawlingSessionAdvertisement", b =>
                {
                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crawling_session_advertisements_advertisements_advertisemen");

                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.CrawlingSession", "CrawlingSession")
                        .WithMany("AffectedAdvertisements")
                        .HasForeignKey("CrawlingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crawling_session_advertisements_crawling_sessions_crawling_");

                    b.Navigation("Advertisement");

                    b.Navigation("CrawlingSession");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.TransportStopExternalId", b =>
                {
                    b.HasOne("Laraue.Apps.RealEstate.DataAccess.Models.TransportStop", "TransportStop")
                        .WithMany("ExternalIds")
                        .HasForeignKey("TransportStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transport_stop_external_ids_transport_stops_transport_stop_");

                    b.Navigation("TransportStop");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.Advertisement", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("TransportStops");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.CrawlingSession", b =>
                {
                    b.Navigation("AffectedAdvertisements");
                });

            modelBuilder.Entity("Laraue.Apps.RealEstate.DataAccess.Models.TransportStop", b =>
                {
                    b.Navigation("ExternalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
